// <autogenerated>
// WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
// DDS version: 3.31.0
// ACE version: 7.1.3
// Running on input file: C:\Dev\testFanuc\RobotStateIdl/IDL\RobotStateIdl.idl
// </autogenerated>

using System;
using System.Linq;
using System.Security;
using System.Collections.Generic;
using System.Runtime.InteropServices;
//using System.Text.Json;
//using System.Text.Json.Serialization;
using OpenDDSharp.Marshaller.Json;
using System.Buffers;
using OpenDDSharp;
using OpenDDSharp.DDS;
using OpenDDSharp.Marshaller;

namespace RobotDDS
{
    #region RobotState Definitions
    public class RobotState
    {
        #region Constants
        internal const string API_DLL = "RobotStateIdlWrapper";
        #endregion

        #region Fields
        string _Clock;
        Int32 _SampleId;
        Double _J1;
        Double _J2;
        Double _J3;
        Double _J4;
        Double _J5;
        Double _J6;
        Double _X;
        Double _Y;
        Double _Z;
        Double _W;
        Double _P;
        Double _R;
        #endregion

        #region Properties
        public string Clock
        {
            get { return _Clock; }
            set { _Clock = value; }
        }

        public Int32 SampleId
        {
            get { return _SampleId; }
            set { _SampleId = value; }
        }

        public Double J1
        {
            get { return _J1; }
            set { _J1 = value; }
        }

        public Double J2
        {
            get { return _J2; }
            set { _J2 = value; }
        }

        public Double J3
        {
            get { return _J3; }
            set { _J3 = value; }
        }

        public Double J4
        {
            get { return _J4; }
            set { _J4 = value; }
        }

        public Double J5
        {
            get { return _J5; }
            set { _J5 = value; }
        }

        public Double J6
        {
            get { return _J6; }
            set { _J6 = value; }
        }

        public Double X
        {
            get { return _X; }
            set { _X = value; }
        }

        public Double Y
        {
            get { return _Y; }
            set { _Y = value; }
        }

        public Double Z
        {
            get { return _Z; }
            set { _Z = value; }
        }

        public Double W
        {
            get { return _W; }
            set { _W = value; }
        }

        public Double P
        {
            get { return _P; }
            set { _P = value; }
        }

        public Double R
        {
            get { return _R; }
            set { _R = value; }
        }
        #endregion 

        #region Constructors
        public RobotState()
        {
            _Clock = string.Empty;
            _SampleId = 0;
            _J1 = 0;
            _J2 = 0;
            _J3 = 0;
            _J4 = 0;
            _J5 = 0;
            _J6 = 0;
            _X = 0;
            _Y = 0;
            _Z = 0;
            _W = 0;
            _P = 0;
            _R = 0;
        }

        public RobotState(OpenDDSharp.Marshaller.Cdr.CdrReader reader, Span<byte> span)
        {
            FromCDR(reader, span);
        }
        #endregion

        #region Methods
        internal void MemberwiseCopy(RobotState source)
        {
            Clock = source.Clock;
            SampleId = source.SampleId;
            J1 = source.J1;
            J2 = source.J2;
            J3 = source.J3;
            J4 = source.J4;
            J5 = source.J5;
            J6 = source.J6;
            X = source.X;
            Y = source.Y;
            Z = source.Z;
            W = source.W;
            P = source.P;
            R = source.R;
        }

        public ReadOnlySpan<byte> ToCDR()
        {
            var writer = new OpenDDSharp.Marshaller.Cdr.CdrWriter();
            writer.WriteString(this.Clock);
            writer.WriteInt32(this.SampleId);
            writer.WriteDouble(this.J1);
            writer.WriteDouble(this.J2);
            writer.WriteDouble(this.J3);
            writer.WriteDouble(this.J4);
            writer.WriteDouble(this.J5);
            writer.WriteDouble(this.J6);
            writer.WriteDouble(this.X);
            writer.WriteDouble(this.Y);
            writer.WriteDouble(this.Z);
            writer.WriteDouble(this.W);
            writer.WriteDouble(this.P);
            writer.WriteDouble(this.R);
            return writer.GetBuffer();
        }

        public ReadOnlySpan<byte> ToCDR(OpenDDSharp.Marshaller.Cdr.CdrWriter writer)
        {
            writer.WriteString(this.Clock);
            writer.WriteInt32(this.SampleId);
            writer.WriteDouble(this.J1);
            writer.WriteDouble(this.J2);
            writer.WriteDouble(this.J3);
            writer.WriteDouble(this.J4);
            writer.WriteDouble(this.J5);
            writer.WriteDouble(this.J6);
            writer.WriteDouble(this.X);
            writer.WriteDouble(this.Y);
            writer.WriteDouble(this.Z);
            writer.WriteDouble(this.W);
            writer.WriteDouble(this.P);
            writer.WriteDouble(this.R);
            return writer.GetBuffer();
        }

        public void FromCDR(Span<byte> span)
        {
            var reader = new OpenDDSharp.Marshaller.Cdr.CdrReader();
            this.Clock = reader.ReadString(span);
            this.SampleId = reader.ReadInt32(span);
            this.J1 = reader.ReadDouble(span);
            this.J2 = reader.ReadDouble(span);
            this.J3 = reader.ReadDouble(span);
            this.J4 = reader.ReadDouble(span);
            this.J5 = reader.ReadDouble(span);
            this.J6 = reader.ReadDouble(span);
            this.X = reader.ReadDouble(span);
            this.Y = reader.ReadDouble(span);
            this.Z = reader.ReadDouble(span);
            this.W = reader.ReadDouble(span);
            this.P = reader.ReadDouble(span);
            this.R = reader.ReadDouble(span);
        }

        public void FromCDR(OpenDDSharp.Marshaller.Cdr.CdrReader reader, Span<byte> span)
        {
            this.Clock = reader.ReadString(span);
            this.SampleId = reader.ReadInt32(span);
            this.J1 = reader.ReadDouble(span);
            this.J2 = reader.ReadDouble(span);
            this.J3 = reader.ReadDouble(span);
            this.J4 = reader.ReadDouble(span);
            this.J5 = reader.ReadDouble(span);
            this.J6 = reader.ReadDouble(span);
            this.X = reader.ReadDouble(span);
            this.Y = reader.ReadDouble(span);
            this.Z = reader.ReadDouble(span);
            this.W = reader.ReadDouble(span);
            this.P = reader.ReadDouble(span);
            this.R = reader.ReadDouble(span);
        }
        #endregion
    }

    public class RobotStateTypeSupport : ITypeSupport<RobotState>
    {
        #region Fields
        // JSON Options removed to fix Unity errors

        private IntPtr _native;

        private readonly ArrayPool<byte> _bytesPool = ArrayPool<byte>.Shared;
        #endregion

        #region Constructors
        public RobotStateTypeSupport()
        {
            _native = RobotStateTypeSupportNative.RobotStateTypeSupportNew();
        }
        #endregion

        #region Methods
        public string GetTypeName()
        {
            return Marshal.PtrToStringAnsi(RobotStateTypeSupportNative.GetTypeName(_native));
        }

        public ReturnCode RegisterType(DomainParticipant dp, string typeName)
        {
            return (ReturnCode)RobotStateTypeSupportNative.RegisterType(_native, dp.ToNative(), typeName);
        }

        public ReturnCode UnregisterType(DomainParticipant dp, string typeName)
        {
            return (ReturnCode)RobotStateTypeSupportNative.UnregisterType(_native, dp.ToNative(), typeName);
        }

        // --- FIX STARTS HERE ---
        // We implement these methods to satisfy the Interface, 
        // but we leave them empty/dummy because we removed the JSON library.

        public string EncodeToString(RobotState sample)
        {
            // Return empty string or throw exception since we aren't using JSON
            return String.Empty;
        }

        public RobotState DecodeFromString(string str)
        {
            // Return null since we aren't using JSON
            return null;
        }
        // --- FIX ENDS HERE ---

        public byte[] EncodeToBytes(RobotState sample)
        {
            var span = sample.ToCDR();

            var bytes = _bytesPool.Rent(span.Length);
            try
            {
                span.CopyTo(bytes);
                return bytes;
            }
            finally
            {
                _bytesPool.Return(bytes);
            }
        }

        public RobotState DecodeFromBytes(byte[] data)
        {
            var sample = new RobotState();
            sample.FromCDR(data);
            return sample;
        }
        #endregion
    }

    [SuppressUnmanagedCodeSecurity]
    internal static partial class RobotStateTypeSupportNative
    {
#if NET8_0_OR_GREATER
        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_new", StringMarshalling = StringMarshalling.Utf8)]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial IntPtr RobotStateTypeSupportNew();

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_GetTypeName", StringMarshalling = StringMarshalling.Utf8)]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial IntPtr GetTypeName(IntPtr native);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_RegisterType", StringMarshalling = StringMarshalling.Utf8)]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int RegisterType(IntPtr native, IntPtr dp, string typeName);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_UnregisterType", StringMarshalling = StringMarshalling.Utf8)]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int UnregisterType(IntPtr native, IntPtr dp, string typeName);
#else
        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_new", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr RobotStateTypeSupportNew();

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_GetTypeName", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Auto, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        internal static extern IntPtr GetTypeName(IntPtr native);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_RegisterType", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        internal static extern int RegisterType(IntPtr native, IntPtr dp, string typeName);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateTypeSupport_UnregisterType", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        internal static extern int UnregisterType(IntPtr native, IntPtr dp, string typeName);
#endif
    }

    // Issue with keywords identifiers "@". Avoid code generator serialization
    // [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Default)]
    // [JsonSerializable(typeof(RobotState))]
    // public partial class RobotStateSerializerContext : JsonSerializerContext
    // {
    // }

    public class RobotStateDataWriter : DataWriter
    {
        #region Fields
        private readonly IntPtr _native;
        private RobotStateTypeSupport _typeSupport;
        #endregion

        #region Constructors
        public RobotStateDataWriter(DataWriter dw) : base(dw.ToNative())
        {
			IntPtr ptr = base.ToNative();
            _native = RobotStateDataWriterNative.Narrow(ptr);

            _typeSupport = new RobotStateTypeSupport();
        }
        #endregion

        #region Methods
        public InstanceHandle RegisterInstance(RobotState instance)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;

            var bytes = _typeSupport.EncodeToBytes(instance);

            ret = RobotStateDataWriterNative.RegisterInstance(_native, bytes, (UIntPtr)bytes.Length);

            return ret;
        }

        public InstanceHandle RegisterInstance(RobotState instance, Timestamp timestamp)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;

            var bytes = _typeSupport.EncodeToBytes(instance);
            var tsBytes = timestamp.ToCDR().ToArray();

            ret = RobotStateDataWriterNative.RegisterInstanceTimestamp(_native, bytes, (UIntPtr)bytes.Length, tsBytes, (UIntPtr)tsBytes.Length);

            return ret;
        }

        public ReturnCode UnregisterInstance(RobotState data)
        {
            InstanceHandle handle = LookupInstance(data);
            if (handle == InstanceHandle.HandleNil)
            {
                return ReturnCode.PreconditionNotMet;
            }

            var bytes = _typeSupport.EncodeToBytes(data);

	        return (ReturnCode)RobotStateDataWriterNative.UnregisterInstance(_native, bytes, (UIntPtr)bytes.Length, handle);
        }

		public ReturnCode UnregisterInstance(RobotState data, InstanceHandle handle)
        {
            var bytes = _typeSupport.EncodeToBytes(data);

            return (ReturnCode)RobotStateDataWriterNative.UnregisterInstance(_native, bytes, (UIntPtr)bytes.Length, handle);
        }

        public ReturnCode UnregisterInstance(RobotState data, InstanceHandle handle, Timestamp timestamp)
        {
            var bytes = _typeSupport.EncodeToBytes(data);
            var tsBytes = timestamp.ToCDR().ToArray();

            return (ReturnCode)RobotStateDataWriterNative.UnregisterInstanceTimestamp(_native, bytes, (UIntPtr)bytes.Length, handle, tsBytes, (UIntPtr)tsBytes.Length);
        }

        public ReturnCode Write(RobotState data)
        {
            return Write(data, InstanceHandle.HandleNil);
        }

        public ReturnCode Write(RobotState data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;

            var bytes = _typeSupport.EncodeToBytes(data);

            ret = (ReturnCode)RobotStateDataWriterNative.Write(_native, bytes, (UIntPtr)bytes.Length, handle);

            return ret;
        }

        public ReturnCode Write(RobotState data, InstanceHandle handle, Timestamp timestamp)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;

            var bytes = _typeSupport.EncodeToBytes(data);
            var tsBytes = timestamp.ToCDR().ToArray();

            ret = (ReturnCode)RobotStateDataWriterNative.WriteWithTimestamp(_native, bytes, (UIntPtr)bytes.Length, handle, tsBytes, (UIntPtr)tsBytes.Length);

            return ret;
        }

        public ReturnCode Dispose(RobotState data)
        {
            return Dispose(data, InstanceHandle.HandleNil);
        }

		public ReturnCode Dispose(RobotState data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;

            var bytes = _typeSupport.EncodeToBytes(data);

            ret = (ReturnCode)RobotStateDataWriterNative.Dispose(_native, bytes, (UIntPtr)bytes.Length, handle);

            return ret;
        }

        public ReturnCode Dispose(RobotState data, InstanceHandle handle, Timestamp timestamp)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;

            var bytes = _typeSupport.EncodeToBytes(data);
            var tsBytes = timestamp.ToCDR().ToArray();

            ret = (ReturnCode)RobotStateDataWriterNative.DisposeTimestamp(_native, bytes, (UIntPtr)bytes.Length, handle, tsBytes, (UIntPtr)tsBytes.Length);

            return ret;
        }

        public ReturnCode GetKeyValue(RobotState data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            if (handle == InstanceHandle.HandleNil)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;

            var size = UIntPtr.Zero;
            var ptr = IntPtr.Zero;

            ret = (ReturnCode)RobotStateDataWriterNative.GetKeyValue(_native, ref ptr, ref size, handle);

            if (ret == ReturnCode.Ok)
            {
                byte[] managedArray = new byte[(int)size];
                Marshal.Copy(ptr, managedArray, 0, (int)size);

                var sample = _typeSupport.DecodeFromBytes(managedArray);
                data.MemberwiseCopy(sample);
            }

            return ret;
        }

        public InstanceHandle LookupInstance(RobotState instance)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;

            var bytes = _typeSupport.EncodeToBytes(instance);

            ret = RobotStateDataWriterNative.LookupInstance(_native, bytes, (UIntPtr)bytes.Length);

            return ret;
        }
        #endregion
     }

    public static partial class RobotStateDataWriterNative
    {
#if NET8_0_OR_GREATER
        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_Narrow")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial IntPtr Narrow(IntPtr dw);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_Write_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int Write(IntPtr dw, byte[] cdrData, UIntPtr size, int handle);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_WriteWithTimestamp_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int WriteWithTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, int handle, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_RegisterInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int RegisterInstance(IntPtr dw, byte[] cdrData, UIntPtr size);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_RegisterInstanceTimestamp_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int RegisterInstanceTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_UnregisterInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int UnregisterInstance(IntPtr dw, byte[] cdrData, UIntPtr size, int handle);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_UnregisterInstanceTimestamp_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int UnregisterInstanceTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, int handle, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_LookupInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int LookupInstance(IntPtr dw, byte[] cdrData, UIntPtr size);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_Dispose_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int Dispose(IntPtr dw, byte[] cdrData, UIntPtr size, int handle);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_DisposeTimestamp_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int DisposeTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, int handle, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_GetKeyValue_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int GetKeyValue(IntPtr dw, ref IntPtr cdrData, ref UIntPtr size, int handle);
#else
        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_Narrow", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr Narrow(IntPtr dw);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_Write_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int Write(IntPtr dw, byte[] cdrData, UIntPtr size, int handle);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_WriteWithTimestamp_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int WriteWithTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, int handle, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_RegisterInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int RegisterInstance(IntPtr dw, byte[] cdrData, UIntPtr size);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_RegisterInstanceTimestamp_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int RegisterInstanceTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_UnregisterInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int UnregisterInstance(IntPtr dw, byte[] cdrData, UIntPtr size, int handle);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_UnregisterInstanceTimestamp_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int UnregisterInstanceTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, int handle, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_LookupInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int LookupInstance(IntPtr dw, byte[] cdrData, UIntPtr size);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_Dispose_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int Dispose(IntPtr dw, byte[] cdrData, UIntPtr size, int handle);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_DisposeTimestamp_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int DisposeTimestamp(IntPtr dw, byte[] cdrData, UIntPtr size, int handle, byte[] tsCdr, UIntPtr tsSize);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataWriter_GetKeyValue_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int GetKeyValue(IntPtr dw, [In, Out] ref IntPtr cdrData, [In, Out] ref UIntPtr size, int handle);
#endif
    }

    public class RobotStateDataReader : DataReader
    {
        #region Fields
        private readonly IntPtr _native;
        private RobotStateTypeSupport _typeSupport;

        private static ArrayPool<SampleInfo> infoPool = ArrayPool<SampleInfo>.Shared;
        private static ArrayPool<RobotState> dataPool = ArrayPool<RobotState>.Shared;
        #endregion

        #region Constructors
        public RobotStateDataReader(DataReader dr) : base(dr.ToNative())
        {
			IntPtr ptr = base.ToNative();
            _native = RobotStateDataReaderNative.Narrow(ptr);

            _typeSupport = new RobotStateTypeSupport();
        }
        #endregion

        #region Methods
        public ReturnCode Read(List<RobotState> receivedData, List<SampleInfo> receivedInfo)
        {
            return Read(receivedData, receivedInfo, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Read(List<RobotState> receivedData, List<SampleInfo> receivedInfo, int maxSamples)
        {
            return Read(receivedData, receivedInfo, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Read(List<RobotState> receivedData, List<SampleInfo> receivedInfo, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.ReadWithCondition(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);
            }

            return ret;
        }

        public ReturnCode Read(List<RobotState> receivedData, List<SampleInfo> receivedInfo, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.Read(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);
            }

            return ret;
        }

        public ReturnCode Take(List<RobotState> receivedData, List<SampleInfo> receivedInfo)
        {
            return Take(receivedData, receivedInfo, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Take(List<RobotState> receivedData, List<SampleInfo> receivedInfo, int maxSamples)
        {
            return Take(receivedData, receivedInfo, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Take(List<RobotState> receivedData, List<SampleInfo> receivedInfo, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.TakeWithCondition(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public unsafe ReturnCode Take(List<RobotState> receivedData, List<SampleInfo> receivedInfo, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.Take(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode ReadInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle)
        {
            return ReadInstance(receivedData, receivedInfo, handle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples)
        {
            return ReadInstance(receivedData, receivedInfo, handle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.ReadInstanceWithCondition(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, (int)handle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode ReadInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.ReadInstance(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, handle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode TakeInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle)
        {
            return TakeInstance(receivedData, receivedInfo, handle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples)
        {
            return TakeInstance(receivedData, receivedInfo, handle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.TakeInstanceWithCondition(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, (int)handle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode TakeInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.TakeInstance(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, handle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode ReadNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle)
        {
            return ReadNextInstance(receivedData, receivedInfo, previousHandle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples)
        {
            return ReadNextInstance(receivedData, receivedInfo, previousHandle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.ReadNextInstanceWithCondition(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, previousHandle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode ReadNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.ReadNextInstance(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, previousHandle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode TakeNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle)
        {
            return TakeNextInstance(receivedData, receivedInfo, previousHandle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples)
        {
            return TakeNextInstance(receivedData, receivedInfo, previousHandle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

           IntPtr ptrData = IntPtr.Zero;
           IntPtr ptrInfo = IntPtr.Zero;
           UIntPtr sizeData = UIntPtr.Zero;
           UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.TakeNextInstanceWithCondition(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, previousHandle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode TakeNextInstance(List<RobotState> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)RobotStateDataReaderNative.TakeNextInstance(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo, previousHandle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !ptrData.Equals(IntPtr.Zero) && !ptrInfo.Equals(IntPtr.Zero))
            {
                ReadOrTakeFromPointer(receivedData, receivedInfo, ptrData, sizeData, ptrInfo, sizeInfo);

                MarshalHelper.ReleaseNativePointer(ptrData);
                MarshalHelper.ReleaseNativePointer(ptrInfo);
            }

            return ret;
        }

        public ReturnCode ReadNextSample(RobotState data, SampleInfo sampleInfo)
        {
            if (data == null || sampleInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ret = (ReturnCode)RobotStateDataReaderNative.ReadNextSample(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo);

            if (ret == ReturnCode.Ok)
            {
                byte[] dataArray = new byte[(int)sizeData];
                Marshal.Copy(ptrData, dataArray, 0, (int)sizeData);

                var sample = _typeSupport.DecodeFromBytes(dataArray);
                data.MemberwiseCopy(sample);

                byte[] infoArray = new byte[(int)sizeInfo];
                Marshal.Copy(ptrInfo, infoArray, 0, (int)sizeInfo);

                sampleInfo.FromCDR(infoArray);
            }

            return ret;
        }

        public ReturnCode TakeNextSample(RobotState data, SampleInfo sampleInfo)
        {
            if (data == null || sampleInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            IntPtr ptrData = IntPtr.Zero;
            IntPtr ptrInfo = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;
            UIntPtr sizeInfo = UIntPtr.Zero;

            ret = (ReturnCode)RobotStateDataReaderNative.TakeNextSample(_native, ref ptrData, ref sizeData, ref ptrInfo, ref sizeInfo);

            if (ret == ReturnCode.Ok)
            {
                byte[] dataArray = new byte[(int)sizeData];
                Marshal.Copy(ptrData, dataArray, 0, (int)sizeData);

                var sample = _typeSupport.DecodeFromBytes(dataArray);
                data.MemberwiseCopy(sample);

                byte[] infoArray = new byte[(int)sizeInfo];
                Marshal.Copy(ptrInfo, infoArray, 0, (int)sizeInfo);

                sampleInfo.FromCDR(infoArray);
            }

            return ret;
        }

        public ReturnCode GetKeyValue(RobotState data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            if (handle == InstanceHandle.HandleNil)
            {
                return ReturnCode.BadParameter;
            }

            IntPtr ptrData = IntPtr.Zero;
            UIntPtr sizeData = UIntPtr.Zero;

            var ret = (ReturnCode)RobotStateDataReaderNative.GetKeyValue(_native, ref ptrData, ref sizeData, handle);

            if (ret == ReturnCode.Ok)
            {
                byte[] managedArray = new byte[(int)sizeData];
                Marshal.Copy(ptrData, managedArray, 0, (int)sizeData);

                var sample = _typeSupport.DecodeFromBytes(managedArray);
                data.MemberwiseCopy(sample);
            }

            return ret;
        }

        public InstanceHandle LookupInstance(RobotState instance)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;

            var bytes = _typeSupport.EncodeToBytes(instance);

            ret = RobotStateDataReaderNative.LookupInstance(_native, bytes, (UIntPtr)bytes.Length);

            return ret;
        }
        #endregion

        private static unsafe void ReadOrTakeFromPointer(List<RobotState> receivedData, List<SampleInfo> receivedInfo, IntPtr ptrData, UIntPtr sizeData, IntPtr ptrInfo, UIntPtr sizeInfo)
        {
            var dataSpan = new Span<byte>(ptrData.ToPointer(), (int)sizeData);
            var reader = new OpenDDSharp.Marshaller.Cdr.CdrReader();
            var total = reader.ReadUInt32(dataSpan);
            receivedData.Capacity = (int)total;

            for (int i = 0; i < total; i++)
            {
                receivedData.Add(new RobotState(reader, dataSpan));
            }

            var infoSpan = new Span<byte>(ptrInfo.ToPointer(), (int)sizeInfo);
            reader = new OpenDDSharp.Marshaller.Cdr.CdrReader();

            total = reader.ReadUInt32(infoSpan);
            receivedInfo.Capacity = (int)total;

            for (int i = 0; i < total; i++)
            {
                receivedInfo.Add(new SampleInfo(reader, infoSpan));
            }
        }
    }

    internal static partial class RobotStateDataReaderNative
    {
#if NET8_0_OR_GREATER
        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_Narrow")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
        internal static partial IntPtr Narrow(IntPtr dr);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_Read_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int Read(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadWithCondition_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int ReadWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_Take_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int Take(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeWithCondition_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int TakeWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int ReadInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadInstanceWithCondition_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int ReadInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int TakeInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeInstanceWithCondition_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int TakeInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadNextInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int ReadNextInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadNextInstanceWithCondition_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int ReadNextInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeNextInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int TakeNextInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeNextInstanceWithCondition_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int TakeNextInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadNextSample_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int ReadNextSample(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeNextSample_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int TakeNextSample(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_LookupInstance_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int LookupInstance(IntPtr dr, byte[] cdrData, UIntPtr sizeData);

        [SuppressUnmanagedCodeSecurity]
        [LibraryImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_GetKeyValue_Cdr")]
        [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvSuppressGCTransition) })]
        internal static partial int GetKeyValue(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, int handle);
#else
        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_Narrow", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr Narrow(IntPtr dr);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_Read_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int Read(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadWithCondition_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int ReadWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_Take_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int Take(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeWithCondition_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int TakeWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int ReadInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadInstanceWithCondition_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int ReadInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int TakeInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeInstanceWithCondition_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int TakeInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadNextInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int ReadNextInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadNextInstanceWithCondition_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int ReadNextInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeNextInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int TakeNextInstance(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeNextInstanceWithCondition_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int TakeNextInstanceWithCondition(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_ReadNextSample_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int ReadNextSample(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_TakeNextSample_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int TakeNextSample(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, ref IntPtr cdrInfo, ref UIntPtr sizeInfo);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_LookupInstance_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int LookupInstance(IntPtr dr, byte[] cdrData, UIntPtr sizeData);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(RobotState.API_DLL, EntryPoint = "RobotDDS_RobotStateDataReader_GetKeyValue_Cdr", CallingConvention = CallingConvention.Cdecl)]
        internal static extern int GetKeyValue(IntPtr dr, ref IntPtr cdrData, ref UIntPtr sizeData, int handle);
#endif
    }
    #endregion

}
